title: Kiara Richardson
description: Pursuing a Master's of Engineering Management and Leadership with a focus in Data Science at Rice University
theme: jekyll-theme-minimal

# Add custom variables for your profile picture
profile_picture: images/ProfilePicture.jpg
